build:
  uri: https://github.com/yersan/eap-operator-tx-recovery-demo
  ref: JBEAP-24814-second-xa-enabled-wip
  s2i:
    featurePacks:
      - org.jboss.eap:eap-datasources-galleon-pack:7.4.0.GA-redhat-00003
    galleonLayers:
      - cloud-server
      - postgresql-driver
  env:
    - name: POSTGRESQL_DRIVER_VERSION
      value: '42.6.0'
deploy:
  enabled: false
